name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./daystar_orientation
        file: ./daystar_orientation/Dockerfile
        push: false
        tags: myapp:latest
        outputs: type=docker,dest=/tmp/myapp.tar

    - name: Output image size
      run: |
        docker load < /tmp/myapp.tar
        echo "Image size:"
        docker image ls myapp:latest --format "{{.Size}}"
